
services:
  app-portal:
    container_name: portal-oportunidades
    
    build: .
    
    ports:
      - "3000:3000"
    
    volumes:
      - ./database:/app/database
      
    env_file:
      - .env
    
    restart: always